export interface GuestHouse {
  id?: number; // Optional as it's generated by backend on create
  name: string;
  address: string;
  city: string;
  state: string;
  country: string;
  description: string;
  amenities: string;
  contactNumber: string;
  email: string;
  imageUrl: string;
  createdAt?: string; // Optional, generated by backend
  updatedAt?: string; // Optional, generated by backend
  totalRooms?: number; // Optional, calculated from rooms data
}